//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinh
    {
        public string MaCauHinh { get; set; }
        public string Ten { get; set; }
        public string GiaTri { get; set; }
        public string Type { get; set; }
        public string NhomThietLap { get; set; }
    }
}
