//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhDaoTao
    {
        public int ID { get; set; }
        public string Icon { get; set; }
        public string TenChuongTrinh { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
    }
}
