//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public Nullable<int> idTaiKhoan { get; set; }
        public Nullable<int> idBaiDang { get; set; }
        public string NoiDung { get; set; }
    
        public virtual BaiDang BaiDang { get; set; }
    }
}
