//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slide()
        {
            this.Slide_HinhAnh = new HashSet<Slide_HinhAnh>();
        }
    
        public int ID { get; set; }
        public string TenSlide { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string LoaiSlide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slide_HinhAnh> Slide_HinhAnh { get; set; }
    }
}
