//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide_HinhAnh
    {
        public int ID { get; set; }
        public int idSlide { get; set; }
        public string TenHinhAnh { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public string LienKet { get; set; }
    
        public virtual Slide Slide { get; set; }
    }
}
